### ISSUE TITLE
Add an image to a new page

### ISSUE THREAD

**Issue by chachoe** [rubenlagus/Telegraph#1]
When creating a new telegraph page, i want to add and Image.. 
How can I add it?

**Comment by kamoddd** [comment]
1. You need url for this image
2. Set necessary attribute SRC for tag IMG and add to content. For example:
` Map<String, String> attrs = new HashMap<>();`
`            attrs.put("src","http://<your url>");`
`            Node imageNode = new NodeElement("img", attrs, new ArrayList<>());`
`            List<Node> tagContent = new ArrayList<>();`
`             tagContent.add(imageNode);`
`            Page page = new CreatePage(account.getAccessToken(), "Simple text", tagContent)`
`                    .setAuthorName("Simple Author")`
`                   .setReturnContent(true)`
`                    .execute();`

**Comment by rubenlagus** [comment]
Closing since it was already answered by @kamoddd, thx
